sudo: true
language: java
jdk: oraclejdk8
cache:
directories:
- $HOME/.m2
install: true
addons:
  apt:
    packages:
    - tightvncserver
    - expect
    - xfonts-base
script:
- export
- bash execute-on-vnc.sh mvn clean verify -Djava.awt.headless=false -Pjacoco coveralls:report