sudo: true
language: java
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
install: true
addons:
  apt:
    packages:
    - tightvncserver
    - expect
    - xfonts-base
  sonarcloud:
    organization: "pinka117-github"
    token:
      secure: "PPjInRjUGkfvQV3i5XzAL/oNNOEPP9WrigiLoS8NXWJWA1uGFTPH6ticyY7tTGpMtMauhh4xfij5doimkrReP4k6HWVDIlTAp5V+TCDmrAliNNSKFu+3QD0VjmmcqYoFvInitBVX9jnKumf9yV2UtQSjW2SOQI/jTeD/DjMfRxVGgrSCN9hakIxaVW9JyOFcOWOK5Tk9wf6g37kb2kTnfejXlgxcrLJOnLMiUeccSh7Vw9rYPX//PCUYNqeQOdvH9IW1NpdNjQscAFxAPNMQKUz8ElZkSTbnfc40lToPOqIV3TNRc1P61cQe1srYKoeRdLpCSDLyv7kBbBfH8X3oyoBrPa5f0v38PrqgiW6I0ZF1gTdBlLQOQv/MqyDNOFzQr1M7K2wPQxr9kf6DaQD3wxp0Ovcj9Wsj7DTrWTBQP5h3dL9rBB/K3NihOY+2B0yHOOXGfmeUVQKMFMimc3x2qvV+SqCiuieuboeTMXVOJhDLXmFHtrP769UvtpeqF7JHvUvjnHej0BIYG7Y0upWIbMUNIfsn6MaUAXn2Rvv08K7Yo2XcdEs1S6wgfttiD1KVBZqAQCeZTXG7h2oBaWyCwC1j8i8K4Y4AFhelaOjyBiDZqpZqnQX76GdCy9A8pnKh0SCjHsWQDgK8Uvr/QNgAt4LLa3+OIKl+nQdlRzNY6/4="
services:
 - docker    
script:
- export
- bash execute-on-vnc.sh mvn -Djava.awt.headless=false clean org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:prepare-agent-integration verify org.jacoco:jacoco-maven-plugin:report org.jacoco:jacoco-maven-plugin:reportintegration sonar:sonar coveralls:report